#######################################################################
# File: configs/alertmanager-prod.yml
#
# Description:
#   Production AlertManager configuration template with escalation
#   policies, notification routing, and alert grouping rules.
#
# Purpose:
#   Provide enterprise-grade alerting configuration for production
#   workloads with PagerDuty integration and intelligent routing.
#
# Notes:
#   - Feature Flag: create_default_rules (default: true)
#     * When enabled: This template is loaded via templatefile() in locals.tf
#     * Applied when environment="production"
#   - Template Variables:
#     * ${environment}: Injected for alert labeling and context
#     * ${region}: Used for regional alert identification
#     * ${slack_webhook_url}: Placeholder for Slack integration
#     * ${pagerduty_service_key}: Placeholder for PagerDuty escalation
#   - Production-specific settings:
#     * Fast response times: group_wait=10s, repeat_interval=1h
#     * Critical alert routing to PagerDuty
#     * Alert inhibition rules to prevent spam
#     * Multi-channel notification (Slack + PagerDuty)
#######################################################################


global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@company.com'
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
    group_wait: 10s
    repeat_interval: 1h
  - match:
      severity: warning
    receiver: 'warning-alerts'
    group_wait: 5m
    repeat_interval: 6h

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/'

- name: 'critical-alerts'
  slack_configs:
  - api_url: '${slack_webhook_url}'
    channel: '#critical-alerts'
    title: 'Critical Alert - ${environment}'
    text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
  pagerduty_configs:
  - service_key: '${pagerduty_service_key}'
    description: 'Critical alert in ${environment}'

- name: 'warning-alerts'
  slack_configs:
  - api_url: '${slack_webhook_url}'
    channel: '#warning-alerts'
    title: 'Warning Alert - ${environment}'
    text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'cluster', 'service']